### ISSUE TITLE
Variable Switch

### ISSUE THREAD

**Issue by pawtur5557** [magnigenie-labs/restropress#1]
1. Hello. How to add variable switch. My client serve 3 dimensions of pizza (in centimeters) How to add (maybe addon from other e-commerce plugin works).
2. I want translate this plugin, in Loco translate i dont found severals texts from site. Please review this - Clear order on basket
Add to cart in addon window

**Comment by kshirodpatel** [comment]
Hello @pawtur5557 ,

Thanks for your your interest in our plugin. I am going through your request by point wise.

1.  For variable switch we are creating an add on for this, which would be available in paid. Hope fully the add on would be available within next month.

2. For translation. We are adding those strings for translation ready in our next version. So that you can translate those strings in your language easily.

Please give us review if you really liked our plugin or support. It really matters a lot for us.
You can leave your review [here](https://wordpress.org/support/plugin/restropress/reviews/#new-post)
